[tool.pylint.messages_control]

disable = [
    "too-many-locals",
    "invalid-name",
    "broad-except",
    "import-error",
    "unused-variable",
    "too-many-arguments",
]

[tool.black]
line-length = 88
experimental-string-processing = true
